export const FETCH_CATEGORIES_LOADING = 'FETCH_CATEGORIES_LOADING'
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE'
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS'
