CREATE DATABASE IF NOT EXISTS test2;
USE test2;

CREATE TABLE IF NOT EXISTS users (
	/* INT UNSIGNED */
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
    surname VARCHAR(150) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(256) NOT NULL
);
